### PR TITLE
Feat #657 Support the tabs to open multiple iterations + Fix #678 Sidebar orientation bug

### LINKED ISSUE #657: Support the tabs to open multiple iterations
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Create a "bigger" ViewModel that handles a collection of the ApplicationBase for the new page

~~Subtasks to achieve this feature:~~ (everything will be done at once)
- ~~#676~~
- ~~#677~~

### Logs

  - [ ] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-WEB: 
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version:

### LINKED ISSUE #676: [Tabs] Implement multiple iterations layout
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
[UI] Create a layout to support multiple tabs. [See the Figma](
https://www.figma.com/file/HExiPH4WmdOhBSv4bXdhrL/comet-interface?type=design&node-id=100%3A3178&mode=design&t=uVvFNZOF1kVNTds7-1)

### Logs

  - [ ] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-WEB: 
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version:

### LINKED ISSUE #678: The sidebar menu needs to be vertical not horizontal. The idea is to save screen esate
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Currently the side menu does not show the icons vertiaclly but horizontally. This means that the idea to save screen estate for working has not yet been achieved.

image

Please refactor such taht the icons are shown vertically and that the width of the side-menu becomes much smaller. Preferably as small as the width of the largest icon

  ### System Configuration
Issue happening in Firefox browser. Chrome and Edge work normally.

- COMET version:
  - [x] COMET-WEB: 5.1.0

### PR DESCRIPTION
**Pull request by joao4all**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Closes #657 Support the tabs to open multiple iterations
Closes #678 The sidebar menu needs to be vertical not horizontal. The idea is to save screen state (issue with firefox specifically)

Screenshot
image

### CODE REVIEW

File: COMETwebapp/ViewModels/Components/Common/OpenTab/OpenTabViewModel.cs [hunk 1]
```diff
@@ -103,10 +104,11 @@ public TabbedApplication SelectedApplication
         /// <summary>
         /// Opens the <see cref="EngineeringModel" /> based on the selected field
         /// </summary>
-        /// <returns>A <see cref="Task" /> containing the operation <see cref="Result" /></returns>
-        public override async Task<Result<Iteration>> OpenSession()
+        /// <returns>A <see cref="Task" /></returns>
+        public async Task OpenTab()
         {
             var result = new Result<Iteration>();
+            var isIteration = this.SelectedApplication?.ViewModelType.IsAssignableTo(typeof(ISingleIterationApplicationBaseViewModel)) == true;
```
Comment (antoineatstariongroup) [inline COMETwebapp/ViewModels/Components/Common/OpenTab/OpenTabViewModel.cs:111]: Could you check based on the fact that the ObjectOfInterest is Iteration? Would be more performant

Comment (joao4all) [reply COMETwebapp/ViewModels/Components/Common/OpenTab/OpenTabViewModel.cs]: Sure! Done in the latest commit :)

**Review by antoineatstariongroup — APPROVED** [review]
